# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, aeson, comonad, dataDefault, exceptions, free, httpClient
, httpClientTls, httpTypes, HUnit, mtl, QuickCheck, rawStringsQq
, resourcet, scientific, testFramework, testFrameworkHunit
, testFrameworkQuickcheck2, text, time, transformers
, unorderedContainers
}:

cabal.mkDerivation (self: {
  pname = "shopify";
  version = "0.0.0.1";
  src = ./.;
  isLibrary = true;
  isExecutable = true;
  buildDepends = [
    aeson comonad dataDefault exceptions free httpClient httpClientTls
    httpTypes mtl resourcet scientific text time transformers
    unorderedContainers
  ];
  testDepends = [
    HUnit QuickCheck rawStringsQq testFramework testFrameworkHunit
    testFrameworkQuickcheck2
  ];
  meta = {
    license = self.stdenv.lib.licenses.unfree;
    platforms = self.ghc.meta.platforms;
  };
})
