# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, aeson, comonad, conduit, free, httpConduit, HUnit, mtl
, QuickCheck, rawStringsQq, resourcet, scientific, testFramework
, testFrameworkHunit, testFrameworkQuickcheck2, text, time
, unorderedContainers
}:

cabal.mkDerivation (self: {
  pname = "shopify";
  version = "0.0.0.1";
  src = ./.;
  buildDepends = [
    aeson comonad conduit free httpConduit mtl resourcet scientific
    text time unorderedContainers
  ];
  testDepends = [
    HUnit QuickCheck rawStringsQq testFramework testFrameworkHunit
    testFrameworkQuickcheck2
  ];
  meta = {
    license = self.stdenv.lib.licenses.unfree;
    platforms = self.ghc.meta.platforms;
  };
})
